---
title: "Predicting Transportation Demand Based on Manufacturing Activity"
author: 
  - Gulamzada, Aysel[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
abstract: |
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 21080060, [Github Repo](https://github.com/ayselgulamzada/21080060)


# Summary

This academic paper presents an analysis of Employment data, focusing on the transportation sector and its relationship with three predictor variables: Manufacturing, Construction, and Mining. The summary statistics for these variables are presented in the first section of the study, together with the mean values, standard deviations, minimal and maximum values, and medians for each variable. The average activity levels, variability, and extremes within the sectors are indicated by these statistics, which also provide insights into the distribution and range of values for each variable.
After that, the study does a multiple linear regression analysis to look at the variables influencing transportation. The coefficients associated with each predictor variable, quantify the expected impact of these variables on transportation. The relative contributions of each predictor variable to the total impact on the transportation industry are useful insights offered by this information. A bar plot is included to visually represent the coefficients, allowing for a quick comparison and identification of the most influential predictors.

Furthermore, the paper explores the correlation between transportation and manufacturing through a scatter plot. This plot visually depicts the relationship between the two variables, with manufacturing values on the x-axis and transportation values on the y-axis. Each data point represents an individual combination of values, and the overall trend is shown by a smoothed line. This visualization helps identify potential relationships or patterns between transportation and manufacturing, as well as understand the distribution of data points.

The paper concludes by presenting the predictions made using the linear regression model. A line plot provides a visual evaluation of the model's prediction accuracy by comparing the projected transportation numbers versus the actual values. The plot presents the transportation values on the y-axis and samples from the dataset on the x-axis. The orange line represents the projected transportation values based on the regression model, while the blue line represents the actual values. With the help of the specified predictor variables, this comparison enables an assessment of how well the model does at anticipating transportation values.

In summary, this academic paper provides a comprehensive analysis of the employment data, focusing on the transportation sector. The regression analysis and correlation plot investigate the factors influencing transportation, while the summary statistics provide a general picture of the distribution and range of values for the predictor variables. The prediction results provide insights into the model's performance in forecasting transportation values. Overall, this research contributes to a better understanding of the relationships and dynamics within the transportation sector and its association with manufacturing, construction, and mining activities.










